apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dshack-development
  name: dshack-local-deploy-config
data:
  # StatefulSetの名前解決 (Pod名.Service名.Namespace名.svc.cluster.local)
  POSTGRES_HOST: postgres-sts-0.postgres-svc.dshack-development.svc.cluster.local
  POSTGRES_PORT: "5432"
  APPLICATION_LOG_PATH: "/var/log/dshacks-development"
---