# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dshack-development
  name: dshack-config
data:
  # StatefulSetの名前解決 (Pod名.Service名.Namespace名.svc.cluster.local)
  POSTGRES_HOST: postgres-sts-0.postgres-svc.dshack-development.svc.cluster.local
  POSTGRES_TEST_HOST: postgres-test-sts-0.postgres-test-svc.dshack-development.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_TEST_PORT: "5432"
  APP_LOG_PATH: ./log/app
  TEST_LOG_PATH: ./log/test
  SQL_LOG_PATH: ./log/sql
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dshack-development-logging
  name: dshack-logging-config
data:
  ELASTICSEARCH_URL: http://elasticsearch:9200
  XPACK_SECURITY_ENABLED: "true"
---

# PostgreSQL (StatefulSet + HeadlessService)
# 開発時には外部のkubernetesクラスター外からもアクセスしたいので、NodePort Serviceも定義する
apiVersion: v1
kind: Service
metadata:
  namespace: dshack-development
  name: postgres-svc
  labels:
    app: postgres-sts
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres-sts
---
apiVersion: v1
kind: Service
metadata:
  namespace: dshack-development
  name: postgres-node-svc
  labels:
    app: postgres-sts
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30010
  selector:
    app: postgres-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dshack-development
  name: postgres-sts
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sts
  template:
    metadata:
      labels:
        app: postgres-sts
    spec:
      containers:
      - name: postgres
        image: postgres:12.1
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-pvc
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---

# PostgreSQL Testing DB (StatefulSet + HeadlessService)
apiVersion: v1
kind: Service
metadata:
  namespace: dshack-development
  name: postgres-test-svc
  labels:
    app: postgres-test-sts
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres-test-sts
---
apiVersion: v1
kind: Service
metadata:
  namespace: dshack-development
  name: postgres-test-node-svc
  labels:
    app: postgres-test-sts
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30011
  selector:
    app: postgres-test-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dshack-development
  name: postgres-test-sts
spec:
  serviceName: postgres-test-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-test-sts
  template:
    metadata:
      labels:
        app: postgres-test-sts
    spec:
      containers:
      - name: postgres
        image: postgres:12.1
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: testdbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-test-pvc
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-test-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---

# ElasticSearch (Deployment + NodePort Service)
# ロギング環境はFluend + ElasticSearch + kibanaで構築する
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dshack-development-logging
  name: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: dshack-development-logging
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30020
---

# kibana
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dshack-development-logging
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.6.0
        envFrom:
          - configMapRef:
              name: dshack-logging-config
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: dshack-development-logging
  name: kibana
  labels:
    service: kibana
spec:
  type: NodePort
  selector:
    run: kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30080
# ---
# TODO: SchemaSpy
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: dshack-development
#   name: schemaspy-svc
#   labels:
#     app: schemaspy-dashboard
# spec:
#   type: NodePort
#   ports:
#   - port: 8080
#     targetPort: 80
#     nodePort: 30080
#   selector:
#     app: schemaspy-dashboard
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   namespace: dshack-development
#   name: schemaspy-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 0.5Gi
#   storageClassName: standard
---
# DB migration job
# Pytest all test job(CI)
apiVersion: batch/v1
kind: Job
metadata:
  namespace: dshack-development
  name: pytest-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: pytest-job
        image: dshacks/pytest-job
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_TEST_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: testdbname
        - name: POSTGRES_TEST_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_TEST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        envFrom:
          - configMapRef:
              name: dshack-config
      restartPolicy: Never
# Pytest smoke test job(CI)