apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: data-infrastructure
build:
  artifacts:
  - image: dshacks/pytest-job
    context: .
deploy:
  kubectl:
    manifests:
    - ./kubernetes/local/credentials/*
    - ./kubernetes/local/autotest/*