apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: data-infrastructure
build:
  artifacts:
  - image: dshacks/pytest-job
deploy:
  kubectl:
    manifests:
    - ./kubernetes/dshack-secret.yaml
    - ./kubernetes/dshack-rbac.yaml
    - ./kubernetes/dshack-db.yaml
    # - ./kubernetes/dshack-logging.yaml  # Spec不足のためローカルでは使用しない
    - ./kubernetes/dshack-local-ci.yaml
