apiVersion: v1
kind: Service
metadata:
  namespace: dshack-infra
  name: postgres
  labels:
    app: postgres-sts
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres-sts