apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dshack-development
  name: dshack-config
data:
  # StatefulSetの名前解決 (Pod名.Service名.Namespace名.svc.cluster.local)
  POSTGRES_HOST: postgres-sts-0.postgres-svc.dshack-development.svc.cluster.local
  POSTGRES_TEST_HOST: postgres-test-sts-0.postgres-test-svc.dshack-development.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_TEST_PORT: "5432"
  APPLICATION_LOG_PATH: "/var/log/dshacks-development"
---
# local CI by skaffold
apiVersion: batch/v1
kind: Job
metadata:
  namespace: dshack-development
  name: pytest-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: pytest-job
        image: dshacks/pytest-job
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_TEST_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: testdbname
        - name: POSTGRES_TEST_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_TEST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        envFrom:
          - configMapRef:
              name: dshack-config
      restartPolicy: Never
